version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src/:/var/www/html/
      - ./apache/myConf.conf:/etc/apache2/sites-available/myConf.conf

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: marseille
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    links:
      - db
